// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxL4mHkqYDRUZgyMBFV3yPwd42sUvi4gY',
    appId: '1:601714610618:web:4b580554c52f9893e84d83',
    messagingSenderId: '601714610618',
    projectId: 'event-staff-52394',
    authDomain: 'event-staff-52394.firebaseapp.com',
    storageBucket: 'event-staff-52394.firebasestorage.app',
    measurementId: 'G-BTF8JZ574L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTrawp7JsCsJDYSd0630A5nCvkOmrVjRY',
    appId: '1:601714610618:android:b1195eba8df77b44e84d83',
    messagingSenderId: '601714610618',
    projectId: 'event-staff-52394',
    storageBucket: 'event-staff-52394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3NbYkkjxybBN5QUcqK4xent0okLESbuk',
    appId: '1:601714610618:ios:8a80a4d02511c70fe84d83',
    messagingSenderId: '601714610618',
    projectId: 'event-staff-52394',
    storageBucket: 'event-staff-52394.firebasestorage.app',
    iosBundleId: 'com.example.eventStaffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3NbYkkjxybBN5QUcqK4xent0okLESbuk',
    appId: '1:601714610618:ios:8a80a4d02511c70fe84d83',
    messagingSenderId: '601714610618',
    projectId: 'event-staff-52394',
    storageBucket: 'event-staff-52394.firebasestorage.app',
    iosBundleId: 'com.example.eventStaffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxL4mHkqYDRUZgyMBFV3yPwd42sUvi4gY',
    appId: '1:601714610618:web:831d4eff49842538e84d83',
    messagingSenderId: '601714610618',
    projectId: 'event-staff-52394',
    authDomain: 'event-staff-52394.firebaseapp.com',
    storageBucket: 'event-staff-52394.firebasestorage.app',
    measurementId: 'G-SK9ZSB362D',
  );
}
